[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = { version = "0.22.7", features = ["serde"] }
num-bigint = "0.4.3"
num-traits = "0.2.15"
numtraits = "0.0.1"
